#!/usr/bin/env node
/**
 * Script to sync version from package.json to frontend version.ts
 * Run this after standard-version or npm version
 */

const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionTsPath = path.join(__dirname, '..', 'apps', 'frontend', 'src', 'app', 'version.ts');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
const version = packageJson.version;

const content = `// Auto-generated file - do not edit manually
// This file is generated by scripts/update-version.js
export const APP_VERSION = '${version}';
`;

fs.writeFileSync(versionTsPath, content);
console.log(`✓ Updated version.ts to ${version}`);
